In [1]:
import numpy as np

##### numerical

In [6]:
data = np.array([2,5,8,4,1,7,4,6,1,2])

In [7]:
np.sort(data)

array([1, 1, 2, 2, 4, 4, 5, 6, 7, 8])

##### alphabetical

In [8]:
data = np.array(["aaa", "aab", "aba", "AAA", "bbc", "bBc", "bbC"])

In [9]:
np.sort(data)

array(['AAA', 'aaa', 'aab', 'aba', 'bBc', 'bbC', 'bbc'], dtype='<U3')

##### boolian

In [10]:
data = np.array([True, False, True, False, False])

In [11]:
np.sort(data)

array([False, False, False,  True,  True])

##### mixed

In [19]:
np.sort([2,5,8,4,1,7,4,6,1,2,True, False, True, False, False])

array([0, 0, 0, 1, 1, 1, 1, 2, 2, 4, 4, 5, 6, 7, 8])

In [20]:
np.sort([2,5,8,4,1,7,4,6,1,2,"aaa", "aab", "aba", "AAA", "bbc", "bBc", "bbC",True, False, True, False, False])

array(['1', '1', '2', '2', '4', '4', '5', '6', '7', '8', 'AAA', 'False',
       'False', 'False', 'True', 'True', 'aaa', 'aab', 'aba', 'bBc',
       'bbC', 'bbc'], dtype='<U11')

##### 2-d array

In [21]:
data = np.array([[2,5,7,6,9],
                 [1,4,8,3,5]])

In [23]:
np.sort(data)

array([[2, 5, 6, 7, 9],
       [1, 3, 4, 5, 8]])